export enum SupportedAssets {
  BTC = 'BTC',
  ETH = 'ETH',
  USDT = 'USDT',
  USDC = 'USDC',
  BNB = 'BNB',
  XRP = 'XRP',
  ADA = 'ADA',
  SOL = 'SOL',
  DOT = 'DOT',
  DOGE = 'DOGE',
  AAVE = 'AAVE',
  BCH = 'BCH',
  COMP = 'COMP',
  DAI = 'DAI',
  LINK = 'LINK',
  MKR = 'MKR',
  SUSHI = 'SUSHI',
  UNI = 'UNI',
  YFI = 'YFI',
  XLM = 'XLM',
  SAND = 'SAND',
  AXS = 'AXS',
  CRV = 'CRV',
  ZRX = 'ZRX',
  KNC = 'KNC',
  AVAX = 'AVAX',
  POL = 'POL',
  DYDX = 'DYDX',
  CHZ = 'CHZ',
  SNX = 'SNX',
  REALX = 'REALX',
  LDO = 'LDO',
  SUMX = 'SUMX',
  NEAR = 'NEAR',
  TIA = 'TIA',
  ARB = 'ARB',
  WLD = 'WLD',
  PENDLE = 'PENDLE',
}

export const SupportedAssetsToCoinGeckoId: Record<SupportedAssets, string> = {
  BTC: 'bitcoin',
  ETH: 'ethereum',
  USDT: 'tether',
  USDC: 'usd-coin',
  BNB: 'binancecoin',
  XRP: 'ripple',
  ADA: 'cardano',
  SOL: 'solana',
  DOT: 'polkadot',
  DOGE: 'dogecoin',
  AAVE: 'aave',
  BCH: 'bitcoin-cash',
  COMP: 'compound-governance-token',
  DAI: 'dai',
  LINK: 'chainlink',
  MKR: 'maker',
  SUSHI: 'sushi',
  UNI: 'uniswap',
  YFI: 'yearn-finance',
  XLM: 'stellar',
  SAND: 'the-sandbox',
  AXS: 'axie-infinity',
  CRV: 'curve-dao-token',
  ZRX: '0x',
  KNC: 'kyber-network-crystal',
  AVAX: 'avalanche-2',
  POL: 'polymath-network',
  DYDX: 'dydx',
  CHZ: 'chiliz',
  SNX: 'synthetix-network-token',
  REALX: 'realx',
  LDO: 'lido-dao',
  SUMX: 'sumx',
  NEAR: 'near',
  TIA: 'celestia',
  ARB: 'arbitrum',
  WLD: 'worldcoin-wld',
  PENDLE: 'pendle',
};
